version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=demeu.settings
